---
galaxy_info:
  description: Install rancher
  role_name: rancher
  author: Cl√©ment Hubert

  license: MLP2

  min_ansible_version: "2.1"

  galaxy_tags:
    - kubernetes
    - rancher
    - management
    - cluster

dependencies: []
