---
galaxy_info:
  description: Install paralus on kubernetes
  role_name: paralus
  author: Cl√©ment Hubert

  license: MLP2

  min_ansible_version: "2.1"

  galaxy_tags:
    - kubernetes
    - paralus

dependencies: []
