---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Remove rancher"
      ansible.builtin.import_role:
        name: "rancher"
  vars:
    rancher_enabled: false
