---
- name: "Remove paralus helm package"
  kubernetes.core.helm:
    name: "{{ paralus_deployment_name }}"
    namespace: "{{ paralus_namespace }}"
    chart_ref: "{{ paralus_helm_chart_ref }}"
    state: "absent"
    wait: true

- name: "Remove paralus namespace"
  kubernetes.core.k8s:
    name: "{{ paralus_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "absent"

- name: "Remove paralus helm repo"
  kubernetes.core.helm_repository:
    name: "{{ paralus_helm_repo_name }}"
    state: "absent"
